import type { TreeNode } from '../types';

export const LIBRARY_TREE: TreeNode[] = [
  {
    id: 'tariff-classification',
    label: 'Tariff Classification',
    icon: 'book',
    children: [
      { id: 'sch-1', label: 'Schedule 1 — Countries & Places', viewKey: 'schedule-1' },
      { id: 'sch-2', label: 'Schedule 2 — Interpretative Rules', viewKey: 'schedule-2' },
      { id: 'sch-3', label: 'Schedule 3 — Classification & Duty Rates', viewKey: 'schedule-3' },
      { id: 'sch-4', label: 'Schedule 4 — Concessional Rates', viewKey: 'schedule-4' },
      { id: 'tco', label: 'Tariff Concession Orders', viewKey: 'tco', apiEndpoint: '/api/tco' },
      { id: 'hsen', label: 'WCO HSEN', viewKey: 'hsen', apiEndpoint: '/api/hsen' },
      { id: 'compendium', label: 'Compendium of Classification', viewKey: 'compendium', apiEndpoint: '/api/compendium' },
      { id: 'precedents', label: 'Classification Precedents', viewKey: 'precedents', apiEndpoint: '/api/precedents' },
      { id: 'alpha-index', label: 'Alphabetical Index', viewKey: 'alpha-index', apiEndpoint: '/api/alpha-index' },
      { id: 'ahecc', label: 'AHECC Export Codes', viewKey: 'ahecc', apiEndpoint: '/api/ahecc' },
    ],
  },
  {
    id: 'customs-legislation',
    label: 'Customs Legislation',
    icon: 'scale',
    children: [
      { id: 'customs-act', label: 'Customs Act 1901', viewKey: 'act', apiEndpoint: '/api/customs-act' },
      { id: 'customs-reg', label: 'Customs Regulation 2015', viewKey: 'customs-reg', apiEndpoint: '/api/customs-reg' },
      { id: 'ct-act', label: 'Customs Tariff Act 1995', viewKey: 'ct-act', apiEndpoint: '/api/ct-act' },
      { id: 'ct-regs', label: 'Customs Tariff Regulations', viewKey: 'ct-regs', apiEndpoint: '/api/ct-regs' },
      { id: 'intl-ob', label: 'International Obligations Reg 2015', viewKey: 'intl-ob', apiEndpoint: '/api/intl-ob' },
    ],
  },
  {
    id: 'dumping',
    label: 'Dumping & Subsidies',
    icon: 'shield',
    children: [
      { id: 'ad-act', label: 'Customs Tariff (Anti-Dumping) Act 1975', viewKey: 'ad-act', apiEndpoint: '/api/ad-act' },
      { id: 'dumping-notices', label: 'Anti-Dumping Notices', viewKey: 'dumping', apiEndpoint: '/api/dumping' },
    ],
  },
  {
    id: 'trade-agreements',
    label: 'Trade Agreements (FTAs)',
    icon: 'globe',
    children: [
      { id: 'fta-4a', label: 'Sch 4A — Singapore (SAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/4a' },
      { id: 'fta-5', label: 'Sch 5 — United States (AUSFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/5' },
      { id: 'fta-6', label: 'Sch 6 — Thailand (TAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/6' },
      { id: 'fta-6a', label: 'Sch 6A — Peru (PAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/6a' },
      { id: 'fta-7', label: 'Sch 7 — Chile (ACI-FTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/7' },
      { id: 'fta-8', label: 'Sch 8 — AANZFTA', viewKey: 'schedule', apiEndpoint: '/api/schedule/8' },
      { id: 'fta-8a', label: 'Sch 8A — Pacific Island (PICTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/8a' },
      { id: 'fta-8b', label: 'Sch 8B — CPTPP', viewKey: 'schedule', apiEndpoint: '/api/schedule/8b' },
      { id: 'fta-9', label: 'Sch 9 — Malaysia (MAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/9' },
      { id: 'fta-9a', label: 'Sch 9A — Indonesia (IA-CEPA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/9a' },
      { id: 'fta-10', label: 'Sch 10 — Korea (KAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/10' },
      { id: 'fta-10a', label: 'Sch 10A — India (AI-ECTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/10a' },
      { id: 'fta-11', label: 'Sch 11 — Japan (JAEPA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/11' },
      { id: 'fta-12', label: 'Sch 12 — China (ChAFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/12' },
      { id: 'fta-13', label: 'Sch 13 — Hong Kong (A-HKFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/13' },
      { id: 'fta-14', label: 'Sch 14 — RCEP', viewKey: 'schedule', apiEndpoint: '/api/schedule/14' },
      { id: 'fta-15', label: 'Sch 15 — United Kingdom (A-UKFTA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/15' },
      { id: 'fta-16', label: 'Sch 16 — UAE (CEPA)', viewKey: 'schedule', apiEndpoint: '/api/schedule/16' },
    ],
  },
  {
    id: 'biosecurity',
    label: 'Biosecurity & Imported Foods',
    icon: 'leaf',
    children: [
      { id: 'bio-act', label: 'Biosecurity Act 2015', viewKey: 'bio-act', apiEndpoint: '/api/bio-act' },
      { id: 'bio-regs', label: 'Biosecurity Regulation 2016', viewKey: 'bio-regs', apiEndpoint: '/api/bio-regs' },
      { id: 'ifc-act', label: 'Imported Food Control Act 1992', viewKey: 'ifc-act', apiEndpoint: '/api/ifc-act' },
      { id: 'ifc-reg', label: 'Imported Food Control Regulation', viewKey: 'ifc-reg', apiEndpoint: '/api/ifc-reg' },
      { id: 'aqis', label: 'AQIS Import Conditions', viewKey: 'aqis', apiEndpoint: '/api/aqis' },
    ],
  },
  {
    id: 'prohibitions',
    label: 'Prohibitions & Restrictions',
    icon: 'ban',
    children: [
      { id: 'pi-regs', label: 'Prohibited Imports Regs 1956', viewKey: 'regulations', apiEndpoint: '/api/regulations' },
      { id: 'pe-regs', label: 'Prohibited Exports Regs 1958', viewKey: 'pe-regs', apiEndpoint: '/api/pe-regs' },
      { id: 'chemicals', label: 'Chemical Index (CWC)', viewKey: 'chemicals', apiEndpoint: '/api/chemicals' },
      { id: 'td-act', label: 'Commerce (Trade Descriptions) Act 1905', viewKey: 'td-act', apiEndpoint: '/api/td-act' },
      { id: 'td-regs', label: 'Commerce (Trade Descriptions) Regs', viewKey: 'td-regs', apiEndpoint: '/api/td-regs' },
      { id: 'il-act', label: 'Illegal Logging Prohibition Act 2012', viewKey: 'il-act', apiEndpoint: '/api/il-act' },
      { id: 'il-reg', label: 'Illegal Logging Prohibition Regulation', viewKey: 'il-reg', apiEndpoint: '/api/il-reg' },
    ],
  },
  {
    id: 'gst-taxes',
    label: 'GST & Other Taxes',
    icon: 'dollar',
    children: [
      { id: 'gst-act', label: 'GST Act 1999', viewKey: 'gst-act', apiEndpoint: '/api/gst-act' },
      { id: 'gst-regs', label: 'GST Regulations 2019', viewKey: 'gst-regs', apiEndpoint: '/api/gst-regs' },
    ],
  },
  {
    id: 'regulatory-policy',
    label: 'Regulatory Policy',
    icon: 'file',
    children: [
      { id: 'acn', label: 'Australian Customs Notices', viewKey: 'acn', apiEndpoint: '/api/acn' },
      { id: 'cpquestions', label: 'Community Protection Questions', viewKey: 'cpquestions', apiEndpoint: '/api/cpquestions' },
      { id: 'reffiles', label: 'ABF Reference Files', viewKey: 'reffiles', apiEndpoint: '/api/reffiles' },
      { id: 'cbp-rulings', label: 'CBP Rulings (US)', viewKey: 'cbp-rulings', apiEndpoint: '/api/cbp-rulings' },
    ],
  },
];
